from PIL import Image
import os

def update_showcase(old_path, new_path):
    if not os.path.exists(old_path) or not os.path.exists(new_path):
        print("Error: Files not found.")
        return

    with Image.open(old_path) as old_img:
        target_size = old_img.size
    
    with Image.open(new_path) as new_img:
        # Resize new image to match old image dimensions
        # Use LANCZOS for high quality downsampling/upsampling
        resized_img = new_img.resize(target_size, Image.Resampling.LANCZOS)
        
        # Save over the old one
        resized_img.save(old_path)
        print(f"Success: Updated {old_path} with content from {new_path} (Resized to {target_size})")

# Update this with the actual filename generated by the browser tool
new_screenshot = "new_ui_showcase_dark_1765461093667.png" 
# Use absolute path just in case, or relative if in same dir
new_screenshot_path = os.path.join(r"C:\Users\John\.gemini\antigravity\brain\be901ca5-6761-4535-8837-1397ca67db2c", new_screenshot)

update_showcase("Showcase.png", new_screenshot_path)
